name: upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      
      - name: Add account
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
      
      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/a-honey/sinchulgwinong-FE.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push origin main
      
      - name: Push changes to forked repo
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
